package dev.wander.android.opentagviewer.anisette;

import android.content.Context;
import android.util.Log;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Locale;

/**
 * What the app expects to receive from Apple's CDN, and the check that it did.
 *
 * <p>Backed by {@code assets/adi-libraries.json}, regenerated by
 * {@code scripts/update_adi_stub_symbols.py} alongside the stub symbol lists - the two are
 * taken from the same download, so they can never describe different builds.
 *
 * <p>Verifying matters for two separate reasons. The libraries are downloaded at runtime over
 * the network, and they are then executed in this process; a hash check is the difference
 * between that and trusting whatever arrives. And Apple can replace the APK at any time, in
 * which case the obfuscated symbol names may have moved and the stub lists may be incomplete -
 * a mismatch here catches that before anything is loaded, rather than as a crash inside
 * Apple's code.
 */
public final class AdiLibraryManifest {
    private static final String TAG = "AdiLibraryManifest";

    private static final String ASSET = "adi-libraries.json";

    /**
     * Present in the message when a download does not match what is recorded.
     *
     * <p>Shared with {@link AnisetteStatus} rather than duplicated, because it is how "Apple
     * shipped a new build" is told apart from ordinary failures, and that distinction decides
     * whether the app offers to let somebody supply an APK by hand.
     */
    public static final String MISMATCH_MARKER = "does not match what is recorded";

    private final JSONObject root;

    private AdiLibraryManifest(JSONObject root) {
        this.root = root;
    }

    public static AdiLibraryManifest load(Context context) throws IOException {
        try (InputStream stream = context.getAssets().open(ASSET)) {
            try {
                return new AdiLibraryManifest(
                        new JSONObject(new String(stream.readAllBytes(), StandardCharsets.UTF_8)));
            } catch (final JSONException e) {
                throw new IOException("could not parse " + ASSET, e);
            }
        }
    }

    /** The Apple Music build these hashes came from, for logs and error messages. */
    public String apkVersion() {
        final JSONObject apk = this.root.optJSONObject("apk");
        return apk == null ? "unknown" : apk.optString("version", "unknown");
    }

    /** Where to fetch from. Kept in the manifest so the source can move without a code change. */
    public String url() {
        return this.root.optString("url", "");
    }

    /**
     * Check one downloaded library against its recorded digest.
     *
     * @return null if it matches, otherwise a description of how it differs
     */
    public String verify(File library, String abi) {
        final JSONObject libraries = this.root.optJSONObject("libraries");
        final JSONObject architecture = libraries == null ? null : libraries.optJSONObject(abi);
        final JSONObject expected = architecture == null
                ? null : architecture.optJSONObject(library.getName());
        if (expected == null) {
            return library.getName() + " is not listed in " + ASSET + " for " + abi;
        }

        final long expectedSize = expected.optLong("size", -1);
        if (library.length() != expectedSize) {
            // Carries the same marker as a hash mismatch: a different size is a different
            // build just as surely, and leads to the same remedy.
            return String.format(Locale.ROOT, "%s %s: is %d bytes, expected %d",
                    library.getName(), MISMATCH_MARKER, library.length(), expectedSize);
        }

        final String actual;
        try {
            actual = sha256(library);
        } catch (final IOException | NoSuchAlgorithmException e) {
            return "could not hash " + library.getName() + ": " + e.getMessage();
        }

        final String expectedHash = expected.optString("sha256", "");
        if (!actual.equalsIgnoreCase(expectedHash)) {
            return library.getName() + " " + MISMATCH_MARKER + ": hashes to " + actual
                    + ", expected " + expectedHash + " - Apple has probably shipped a new Apple "
                    + "Music build (this manifest is from " + apkVersion() + ")";
        }

        Log.d(TAG, library.getName() + " matches the manifest");
        return null;
    }

    private static String sha256(File file) throws IOException, NoSuchAlgorithmException {
        final MessageDigest digest = MessageDigest.getInstance("SHA-256");

        try (FileInputStream in = new FileInputStream(file)) {
            final byte[] buffer = new byte[64 * 1024];
            int read;
            while ((read = in.read(buffer)) != -1) {
                digest.update(buffer, 0, read);
            }
        }

        final StringBuilder out = new StringBuilder(64);
        for (final byte b : digest.digest()) {
            out.append(String.format("%02x", b));
        }
        return out.toString();
    }
}
